//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaHuellitas.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class CAMA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAMA()
        {
            this.HOSPITALIZACIONs = new HashSet<HOSPITALIZACION>();
        }
    
        public int id_cama { get; set; }
        public int id_sede { get; set; }
        public string numero_identificador { get; set; }
        public string tipo_cama { get; set; }
        public string estado { get; set; }

        [JsonIgnore]
        public virtual SEDE SEDE { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOSPITALIZACION> HOSPITALIZACIONs { get; set; }
    }
}
