//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaHuellitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIRUGIA
    {
        public int id_cirugia { get; set; }
        public int id_mascota { get; set; }
        public int id_tipo_cirugia { get; set; }
        public int id_empleado_cirujano { get; set; }
        public int id_sede { get; set; }
        public System.DateTime fecha_hora_programada { get; set; }
        public string estado { get; set; }
        public string informe_quirurgico { get; set; }
        public Nullable<int> id_historial_medico_asociado { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual HISTORIAL_MEDICO HISTORIAL_MEDICO { get; set; }
        public virtual MASCOTA MASCOTA { get; set; }
        public virtual SEDE SEDE { get; set; }
        public virtual TIPO_CIRUGIA TIPO_CIRUGIA { get; set; }
    }
}
