//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaHuellitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITA
    {
        public int id_cita { get; set; }
        public int id_mascota { get; set; }
        public int id_empleado_asignado { get; set; }
        public int id_sede { get; set; }
        public int id_tipo_cita { get; set; }
        public System.DateTime fecha_hora_cita { get; set; }
        public string estado { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> id_historial_medico_asociado { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual HISTORIAL_MEDICO HISTORIAL_MEDICO { get; set; }
        public virtual MASCOTA MASCOTA { get; set; }
        public virtual SEDE SEDE { get; set; }
        public virtual TIPO_CITA TIPO_CITA { get; set; }
    }
}
