//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaHuellitas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VeterinariaEntities : DbContext
    {
        public VeterinariaEntities()
            : base("name=VeterinariaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAMA> CAMAs { get; set; }
        public virtual DbSet<CARGO_EMPLEADO> CARGO_EMPLEADO { get; set; }
        public virtual DbSet<CIRUGIA> CIRUGIAs { get; set; }
        public virtual DbSet<CITA> CITAs { get; set; }
        public virtual DbSet<DETALLE_FACTURA> DETALLE_FACTURA { get; set; }
        public virtual DbSet<DETALLE_ORDEN_COMPRA> DETALLE_ORDEN_COMPRA { get; set; }
        public virtual DbSet<DUENO> DUENOes { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADOes { get; set; }
        public virtual DbSet<ESPECIE_MASCOTA> ESPECIE_MASCOTA { get; set; }
        public virtual DbSet<FACTURA> FACTURAs { get; set; }
        public virtual DbSet<HISTORIAL_MEDICO> HISTORIAL_MEDICO { get; set; }
        public virtual DbSet<HOSPITALIZACION> HOSPITALIZACIONs { get; set; }
        public virtual DbSet<MASCOTA> MASCOTAs { get; set; }
        public virtual DbSet<METODO_PAGO> METODO_PAGO { get; set; }
        public virtual DbSet<ORDEN_COMPRA> ORDEN_COMPRA { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTOes { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDORs { get; set; }
        public virtual DbSet<RAZA_MASCOTA> RAZA_MASCOTA { get; set; }
        public virtual DbSet<ROL> ROLs { get; set; }
        public virtual DbSet<SEDE> SEDEs { get; set; }
        public virtual DbSet<SERVICIO_ADICIONAL_PRESTADO> SERVICIO_ADICIONAL_PRESTADO { get; set; }
        public virtual DbSet<STOCK_PRODUCTO_SEDE> STOCK_PRODUCTO_SEDE { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TIPO_CIRUGIA> TIPO_CIRUGIA { get; set; }
        public virtual DbSet<TIPO_CITA> TIPO_CITA { get; set; }
        public virtual DbSet<TIPO_PRODUCTO> TIPO_PRODUCTO { get; set; }
        public virtual DbSet<TIPO_SERVICIO_ADICIONAL> TIPO_SERVICIO_ADICIONAL { get; set; }
        public virtual DbSet<TRATAMIENTO_APLICADO> TRATAMIENTO_APLICADO { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
        public virtual DbSet<USUARIO_ROL> USUARIO_ROL { get; set; }
    }
}
