//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaHuellitas.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    public partial class FACTURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTURA()
        {
            this.DETALLE_FACTURA = new HashSet<DETALLE_FACTURA>();
        }
    
        public int id_factura { get; set; }
        public int id_dueno { get; set; }
        public int id_empleado_emite { get; set; }
        public int id_sede { get; set; }
        public Nullable<int> id_metodo_pago { get; set; }
        public Nullable<System.DateTime> fecha_emision { get; set; }
        public string numero_factura { get; set; }
        public Nullable<decimal> subtotal_factura { get; set; }
        public Nullable<decimal> impuestos_factura { get; set; }
        public Nullable<decimal> descuento_factura { get; set; }
        public Nullable<decimal> total_factura { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public string observaciones { get; set; }        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_FACTURA> DETALLE_FACTURA { get; set; }
        [JsonIgnore]
        public virtual DUENO DUENO { get; set; }
        [JsonIgnore]
        public virtual EMPLEADO EMPLEADO { get; set; }
        [JsonIgnore]
        public virtual METODO_PAGO METODO_PAGO { get; set; }
        [JsonIgnore]
        public virtual SEDE SEDE { get; set; }
    }
}
