//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaHuellitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOSPITALIZACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOSPITALIZACION()
        {
            this.TRATAMIENTO_APLICADO = new HashSet<TRATAMIENTO_APLICADO>();
        }
    
        public int id_hospitalizacion { get; set; }
        public int id_mascota { get; set; }
        public int id_empleado_responsable { get; set; }
        public int id_sede { get; set; }
        public Nullable<int> id_cama_asignada { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public Nullable<System.DateTime> fecha_salida_estimada { get; set; }
        public Nullable<System.DateTime> fecha_salida_real { get; set; }
        public string motivo_ingreso { get; set; }
        public string estado_actual { get; set; }
        public Nullable<int> id_historial_medico_ingreso { get; set; }
    
        public virtual CAMA CAMA { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual HISTORIAL_MEDICO HISTORIAL_MEDICO { get; set; }
        public virtual MASCOTA MASCOTA { get; set; }
        public virtual SEDE SEDE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRATAMIENTO_APLICADO> TRATAMIENTO_APLICADO { get; set; }
    }
}
