//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace VeterinariaHuellitas.Models
{
    public partial class ORDEN_COMPRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDEN_COMPRA()
        {
            this.DETALLE_ORDEN_COMPRA = new HashSet<DETALLE_ORDEN_COMPRA>();
        }
    
        public int id_orden_compra { get; set; }
        public int id_proveedor { get; set; }
        public int id_empleado_solicita { get; set; }
        public int id_sede_destino { get; set; }
        public Nullable<System.DateTime> fecha_orden { get; set; }
        public string estado { get; set; }
        public string observaciones { get; set; }
    
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_ORDEN_COMPRA> DETALLE_ORDEN_COMPRA { get; set; }

        [JsonIgnore]
        public virtual EMPLEADO EMPLEADO { get; set; }

        [JsonIgnore]
        public virtual PROVEEDOR PROVEEDOR { get; set; }

        [JsonIgnore]
        public virtual SEDE SEDE { get; set; }
    }
}
