//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaHuellitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.DETALLE_ORDEN_COMPRA = new HashSet<DETALLE_ORDEN_COMPRA>();
            this.STOCK_PRODUCTO_SEDE = new HashSet<STOCK_PRODUCTO_SEDE>();
            this.TRATAMIENTO_APLICADO = new HashSet<TRATAMIENTO_APLICADO>();
        }
    
        public int id_producto { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int id_tipo_producto { get; set; }
        public string codigo_barras { get; set; }
        public Nullable<decimal> precio_venta_sugerido { get; set; }
        public Nullable<bool> requiere_receta { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_ORDEN_COMPRA> DETALLE_ORDEN_COMPRA { get; set; }
        public virtual TIPO_PRODUCTO TIPO_PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_PRODUCTO_SEDE> STOCK_PRODUCTO_SEDE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRATAMIENTO_APLICADO> TRATAMIENTO_APLICADO { get; set; }
    }
}
