//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaHuellitas.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    public partial class STOCK_PRODUCTO_SEDE
    {
        public int id_stock_producto_sede { get; set; }
        public int id_sede { get; set; }
        public int id_producto { get; set; }
        public int cantidad_disponible { get; set; }
        public Nullable<int> stock_minimo { get; set; }
        public string lote { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
        public Nullable<System.DateTime> ultima_actualizacion { get; set; }
    
        [JsonIgnore]
        public virtual PRODUCTO PRODUCTO { get; set; }
        [JsonIgnore]
        public virtual SEDE SEDE { get; set; }
    }
}
