//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaHuellitas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRATAMIENTO_APLICADO
    {
        public int id_tratamiento_aplicado { get; set; }
        public int id_historial_medico { get; set; }
        public Nullable<int> id_hospitalizacion { get; set; }
        public int id_producto { get; set; }
        public int id_empleado_aplica { get; set; }
        public Nullable<System.DateTime> fecha_hora_aplicacion { get; set; }
        public Nullable<decimal> cantidad_aplicada { get; set; }
        public string unidad_medida { get; set; }
        public string observaciones { get; set; }
        public Nullable<decimal> costo_tratamiento { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual HISTORIAL_MEDICO HISTORIAL_MEDICO { get; set; }
        public virtual HOSPITALIZACION HOSPITALIZACION { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
