//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace VeterinariaHuellitas.Models
{
    public partial class USUARIO_ROL
    {
        public int id_usuario_rol { get; set; }
        public int id_usuario { get; set; }
        public int id_rol { get; set; }
        public Nullable<System.DateTime> fecha_asignacion { get; set; }
    
        [JsonIgnore]
        public virtual ROL ROL { get; set; }
        [JsonIgnore]
        public virtual USUARIO USUARIO { get; set; }
    }
}
